package: nb_anacondacloud

platform:
  - linux-64
  - osx-64
  - win-64

engine:
  - python=2.7
  - python=3.4
  - python=3.5

install:
  - conda build conda.recipe -c anaconda-notebook
  - conda install nb_anacondacloud --use-local -c anaconda-notebook

test:
  - python -m unittest discover

build_targets: conda
