package:
  name: nb_anacondacloud
  version: 0.1.1

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}{{ environ.get('PY_VER').replace('.', '') }}_0{% else %}{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

requirements:
  build:
    - anaconda-client
    - nbsetuptools
    - python
    - setuptools
  run:
    - anaconda-client
    - nb_config_manager
    - nbsetuptools
    - notebook
    - pyyaml
    - python

test:
  files:
    - package.json
  requires:
    - anaconda-client
    - coverage
    - flake8
    - fontconfig              [linux]
    - freetype
    - funcsigs
    - mock
    - nb_config_manager
    - nbsetuptools
    - nodejs
    - nose
    - notebook
    - phantomjs               [linux]
    - python
    - pyyaml
    - requests

source:
  path: ../

about:
  home: https://github.com/Anaconda-Server/nb_anacondacloud
  license: BSD
